import {readFile,writeFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const m=JSON.parse(await readFile('manifest.json','utf8'));
const zip=`dist/${m.id}-${m.version}.zip`;
const files=execFileSync('unzip',['-Z1',zip],{encoding:'utf8'}).trim().split('\n').filter(p=>!p.endsWith('/')).sort();
const expected=['main.js','manifest.json','styles.css','README.md','LICENSE','THIRD_PARTY_NOTICES.md'].map(p=>m.id+'/'+p).sort();
assert.deepEqual(files,expected);
const bundled=execFileSync('unzip',['-p',zip,m.id+'/main.js']);
assert.deepEqual(bundled,await readFile('main.js'));
assert.deepEqual(JSON.parse(execFileSync('unzip',['-p',zip,m.id+'/manifest.json'],{encoding:'utf8'})),m);
const calls=[];const module={exports:{}};
vm.runInNewContext(bundled.toString('utf8'),{module,exports:module.exports,require(name){calls.push(name);assert.equal(name,'obsidian');return {Plugin:class{},PluginSettingTab:class{}};},TextDecoder,TextEncoder,Uint8Array,URL,Headers,setTimeout,clearTimeout},{timeout:5000});
assert.equal(typeof module.exports.default,'function');
assert.equal(typeof module.exports.default.prototype.onload,'function');
assert.equal(typeof module.exports.default.prototype.onunload,'function');
const result={passed:true,version:m.version,files,externalModules:[...new Set(calls)],bytes:bundled.length,sha256:createHash('sha256').update(await readFile(zip)).digest('hex')};
await writeFile('reports/package-check.json',JSON.stringify(result,null,2));
console.log(JSON.stringify(result));
